Fix TSLint errors (except not allow empty block). Fix error
- Fixes `error TS2564: Property '__PHANTOM__' has no initializer and is not definitely assigned in the constructor` due to strictPropertyInitialization